#!/usr/bin/env python3
"""
make_chemistry_jax.py — generates src/chemistry_jax.py from a VULCAN network file.

Usage:
    python make_chemistry_jax.py

Reads the network specified in vulcan_cfg.network and writes
src/chemistry_jax.py, which provides JAX-native drop-in replacements for
chem_funs.chemdf and chem_funs.neg_symjac.

Run this whenever the chemical network changes, before running vulcan.py.
The workflow mirrors make_chem_funs.py:

    python make_chem_funs.py      # renumber network file + generate chem_funs.py
    python make_chemistry_jax.py  # generate chemistry_jax.py from same network
    python vulcan.py              # run simulation
"""

import os
import sys

_root = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_root, 'src'))
import vulcan_cfg

_OFNAME = os.path.join(_root, 'src', 'chemistry_jax.py')


# ---------------------------------------------------------------------------
# Network parser
# ---------------------------------------------------------------------------

def parse_network(path):
    """Parse a VULCAN network file and return (chem_dict, reactions).

    chem_dict : {species_name: index}  in first-appearance order
    reactions : list of (j, reac, prod, rxn_str)
        j        forward reaction index, sequential 1, 3, 5, ... matching
                  the k[i] keys that rates.py builds when it reads the file
        reac     [[stoi, name], ...]  all reactants, including M if present
        prod     [[stoi, name], ...]  all products,  including M if present
        rxn_str  raw "A + B -> C + D" string for comments
    """
    chem_dict = {}
    reactions = []
    j = -1          # becomes 1 on first reaction (j += 2)

    re_end = False

    with open(path) as f:
        for raw in f:
            line = raw.strip()

            if line.startswith('# re_end'):
                re_end = True
                continue
            if re_end:
                continue
            if line.startswith('#') or not line:
                continue

            # Extract content between first '[' and last ']'.
            inner = raw.partition('[')[-1].rpartition(']')[0].strip()
            if not inner:
                continue

            j += 2  # sequential forward index: 1, 3, 5, ...

            reac, prod, reading_reactants = [], [], True
            for token in inner.split():
                if token == '+':
                    continue
                if token == '->':
                    reading_reactants = False
                    continue

                parts = token.split('*')
                if len(parts) == 1:
                    stoi, name = 1, parts[0]
                else:
                    stoi, name = int(parts[0]), parts[1]

                if name != 'M' and name not in chem_dict:
                    chem_dict[name] = len(chem_dict)

                if reading_reactants:
                    reac.append([stoi, name])
                else:
                    prod.append([stoi, name])

            reactions.append((j, reac, prod, inner))

    return chem_dict, reactions


# ---------------------------------------------------------------------------
# Expression builders
# ---------------------------------------------------------------------------

def _rate_expr(species_list, k_idx, chem_dict):
    """Return "k[k_idx]*y[i]*y[j]*M*..." for a reactant or product list."""
    s = f"k[{k_idx}]"
    for stoi, name in species_list:
        if name == 'M':
            s += "*M" if stoi == 1 else f"*M**{stoi}"
        else:
            idx = chem_dict[name]
            s += f"*y[{idx}]" if stoi == 1 else f"*y[{idx}]**{stoi}"
    return s


def build_species_terms(chem_dict, reactions):
    """Return {species_idx: [(term_str, j, rxn_str), ...]} for every species."""
    ni = len(chem_dict)
    terms = {i: [] for i in range(ni)}

    for j, reac, prod, rxn_str in reactions:
        fwd = _rate_expr(reac, j,   chem_dict)
        rev = _rate_expr(prod, j+1, chem_dict)
        v_exp = f"{fwd} - {rev}"

        reac_noM = [(s, n) for s, n in reac if n != 'M']
        prod_noM = [(s, n) for s, n in prod if n != 'M']

        for stoi, name in reac_noM:
            idx = chem_dict[name]
            t = f"-({v_exp})" if stoi == 1 else f"-{stoi}*({v_exp})"
            terms[idx].append((t, j, rxn_str))

        for stoi, name in prod_noM:
            idx = chem_dict[name]
            t = f"+({v_exp})" if stoi == 1 else f"+{stoi}*({v_exp})"
            terms[idx].append((t, j, rxn_str))

    return terms


# ---------------------------------------------------------------------------
# File generator
# ---------------------------------------------------------------------------

_HEADER = '''\
"""JAX-native chemistry functions for neoVULCAN.

AUTO-GENERATED by make_chemistry_jax.py — do not edit by hand.
Network : {network}
Species : {ni}    Reactions (fwd+rev): {nr}
"""

import numpy as np
import jax
import jax.numpy as jnp
from scipy.linalg import block_diag as _scipy_block_diag

# Enable 64-bit floats (JAX defaults to float32; VULCAN uses float64 throughout).
jax.config.update("jax_enable_x64", True)
# Force chemistry evaluation onto CPU.  For single long runs the overhead of
# moving data to a GPU exceeds any kernel speedup.
jax.config.update("jax_default_device", jax.devices("cpu")[0])


# ---------------------------------------------------------------------------
# Single-layer chemistry:  y(ni,), M(scalar), k(nr+1,)  ->  dydt(ni,)
# ---------------------------------------------------------------------------
# k is 1-indexed (k[0] unused); y is 0-indexed (y[0]..y[{ni_1}]).

def _chemdf_single(y, M, k):
    dy = jnp.stack([
'''

_FOOTER = '''\
    ])
    return dy


# ---------------------------------------------------------------------------
# JIT-compiled vmapped versions
# ---------------------------------------------------------------------------

# Vectorise over atmospheric layers.
# Calling convention:  y(nz,ni), M(nz,), k_array(nr+1,nz)  ->  dydt(nz,ni)
_chemdf_vmap = jax.vmap(_chemdf_single, in_axes=(0, 0, 1))
chemdf_jax   = jax.jit(_chemdf_vmap)

# Jacobian d(dydt_i)/d(y_j) for a single layer  ->  (ni, ni)
# jacfwd uses forward-mode AD: ni pushforwards for an (ni,)->(ni,) function.
_jac_single = jax.jacfwd(_chemdf_single, argnums=0)
_jac_vmap   = jax.vmap(_jac_single, in_axes=(0, 0, 1))
_jac_jit    = jax.jit(_jac_vmap)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def k_dict_to_array(k_dict):
    """Convert k dict {{1..nr: array(nz)}} to a (nr+1, nz) numpy array."""
    nr  = max(k_dict.keys())
    nz  = len(next(iter(k_dict.values())))
    arr = np.zeros((nr + 1, nz), dtype=np.float64)
    for i, v in k_dict.items():
        arr[i] = v
    return arr


# ---------------------------------------------------------------------------
# Drop-in replacements for chem_funs.chemdf and chem_funs.neg_symjac
# ---------------------------------------------------------------------------

def chemdf(y, M, k_dict):
    """Drop-in for chem_funs.chemdf(y, M, k).

    y      : (nz, ni) numpy array
    M      : (nz,)    numpy array
    k_dict : dict {{reaction_index: array(nz)}}

    Returns (nz, ni) numpy array of dn/dt from chemistry.
    """
    k_arr = k_dict_to_array(k_dict)
    return np.asarray(chemdf_jax(jnp.asarray(y),
                                 jnp.asarray(M),
                                 jnp.asarray(k_arr)))


def chem_jac_blocks(y, M, k_dict):
    """Return the chemistry Jacobian as a (nz, ni, ni) numpy array.

    Each jac[iz] is the positive Jacobian d(dy/dt)/dy for layer iz.
    Caller is responsible for signs and for assembling into the LHS matrix.
    """
    k_arr = k_dict_to_array(k_dict)
    return np.array(_jac_jit(jnp.asarray(y),
                             jnp.asarray(M),
                             jnp.asarray(k_arr)))   # writable copy


def neg_achemjac(y, M, k_dict):
    """Drop-in for chem_funs.neg_symjac(y, M, k).

    Returns the *negative* chemistry Jacobian as a dense (ni*nz, ni*nz)
    NumPy array (block-diagonal; diffusion coupling added by the caller).
    """
    nz, ni = y.shape
    k_arr  = k_dict_to_array(k_dict)

    jac_blocks = _jac_jit(jnp.asarray(y),
                          jnp.asarray(M),
                          jnp.asarray(k_arr))         # (nz, ni, ni)
    jac_np = np.asarray(jac_blocks)                   # back to CPU NumPy

    # Negate the small (nz, ni, ni) blocks (0.94 MB) before building the
    # (ni*nz, ni*nz) block-diagonal (118 MB) to avoid a second large pass.
    return _scipy_block_diag(*(-jac_np))
'''


def generate(chem_dict, reactions, ofname):
    ni = len(chem_dict)
    nr = 2 * len(reactions)
    idx_to_name = {v: k for k, v in chem_dict.items()}
    sp_terms = build_species_terms(chem_dict, reactions)

    out = []
    out.append(_HEADER.format(
        network=vulcan_cfg.network,
        ni=ni,
        nr=nr,
        ni_1=ni - 1,
    ))

    INDENT = '        '  # 8 spaces — inside jnp.stack([...])

    for sp_idx in range(ni):
        name = idx_to_name[sp_idx]
        term_list = sp_terms[sp_idx]
        out.append(f'{INDENT}# {name} ({sp_idx})\n')

        if not term_list:
            # Species with no chemistry (placeholder so jnp.stack doesn't fail)
            out.append(f'{INDENT}jnp.array(0.),\n')
        else:
            for k_idx, (term, j, rxn_str) in enumerate(term_list):
                is_last = k_idx == len(term_list) - 1
                suffix = ',' if is_last else ''
                out.append(f'{INDENT}{term}{suffix}  # R{j}: {rxn_str}\n')

    out.append(_FOOTER)

    content = ''.join(out)
    with open(ofname, 'w') as f:
        f.write(content)

    print(f"Wrote {ofname}")
    print(f"  {ni} species, {nr} reactions (fwd+rev)")
    print(f"  Network: {vulcan_cfg.network}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    print(f"Parsing network: {vulcan_cfg.network}")
    chem_dict, reactions = parse_network(vulcan_cfg.network)
    generate(chem_dict, reactions, _OFNAME)
