#!/usr/bin/env python

# ==============================================================================
# This is the main file of VULCAN: the chemical kinetics code.                      
# Copyright (C) 2016 Shang-Min Tsai (Shami)                                      
#
# To run VULCAN simply run this file with python.                              
# 
# Requirements:
# - Python and the following packages:
#   pyfastchem
#   numpy 
#   scipy
#   Sympy
#   matplotlib 
#   PIL/Pillow (optional)
# - Following files in the same directory:
#   build_atm.py
#   chemistry_jax.py  (auto-generated by make_chemistry_jax.py)
#   NCHO_photo_network.txt (or other text file for the chemical network)
#   make_chemistry_jax.py
#   store.py
#   vulcan.py
#   vulcan_cfg.py
#   
# - Subdirectories:
#   /atm/ - for the atmospheric input files
#   /output/ - the default directory for the binary output files  
#   /plot/ - for plots
#   /thermo/ - for thermodynamic data
#
# ============================================================================== 
#     VULCAN is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     VULCAN is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You find a copy of the GNU General Public License in the main VULCAN
#     directory under <GPL_license.txt>. If not, see <http://www.gnu.org/licenses/>.
# ==============================================================================
# ============ \V/ ========== Live long and prosper! ========== \V/ ============

# needs to be placed before numpy is imported
# Limiting the number of threads
import os, sys
os.environ["OMP_NUM_THREADS"] = "1"

# --- CLI args & config load -------------------------------------------------
# Must happen before any src/ module is imported: those modules `import vulcan_cfg`
# at module top, which routes through a shim that requires set_cfg() to have run.
import argparse
_argp = argparse.ArgumentParser(description='Run neoVULCAN chemical kinetics simulation.')
_argp.add_argument('-c', '--config', default='vulcan_cfg.toml',
                   help='Path to TOML config file (default: vulcan_cfg.toml next to vulcan.py)')
_argp.add_argument('-n', '--no-remake-chemistry', action='store_true',
                   help='Skip regenerating chemistry_jax.py')
_args = _argp.parse_args()

# Setting the current working directory to the script location (mirrors legacy)
abspath = os.path.abspath(sys.argv[0])
dname = os.path.dirname(abspath)
os.chdir(dname)

# Make internal modules in src/ importable
_src = os.path.join(dname, 'src')
if _src not in sys.path:
    sys.path.insert(0, _src)

# Load TOML config and install as process singleton before src/ imports.
from neovulcan_config import VulcanConfig
from neovulcan_runtime import set_cfg
_cfg = VulcanConfig.from_toml(_args.config, base_dir=dname)
set_cfg(_cfg)

# Regenerate chemistry_jax.py unless suppressed
if not _args.no_remake_chemistry:
    print('Making chemistry_jax.py ...')
    import subprocess
    subprocess.run(
        [sys.executable, 'make_chemistry_jax.py', '-c', _args.config],
        check=True,
    )

# import public modules
import numpy as np
import matplotlib.pyplot as pltslope_min
import matplotlib.legend as lg
import scipy
import scipy.optimize as sop
import time, timeit
import ast

# import VULCAN modules
import store, build_atm
import chemistry_jax as chem_funs

from rates import ReadRate
from integration import Integration
from ros2 import Ros2
from rodas3 import Rodas3
from ode_solver import ODESolver
from output import Output

from phy_const import kb, Navo  # noqa: F401

from chemistry_jax import ni, nr  # number of species and reactions in the network
np.set_printoptions(threshold=np.inf)  # print all for debuging

species = chem_funs.spec_list

### creat the instances for storing the variables and parameters
data_var = store.Variables()
data_atm = store.AtmData()
data_para = store.Parameters()

# record starting CPU time
data_para.start_time = time.time()

make_atm = build_atm.Atm()

# for plotting and printing
output = Output()

# saving the config file
output.save_cfg(dname)

# construct pico
data_atm = make_atm.f_pico(data_atm)
# construct Tco and Kzz 
data_atm =  make_atm.load_TPK(data_atm)
# construct Dzz (molecular diffusion)

# calculating the saturation pressure
if _cfg.condensation.use_condense: make_atm.sp_sat(data_atm)

# for reading rates
rate = ReadRate()

# read-in network and calculating forward rates
data_var = rate.read_rate(data_var, data_atm)

# for low-T rates e.g. Jupiter       
if _cfg.network.use_lowT_limit_rates: data_var = rate.lim_lowT_rates(data_var, data_atm)
    
# reversing rates
data_var = rate.rev_rate(data_var, data_atm)
# removing rates
data_var = rate.remove_rate(data_var)

ini_abun = build_atm.InitialAbun()
# initialing y and ymix (the number density and the mixing ratio of every species)
data_var = ini_abun.ini_y(data_var, data_atm)

# storing the initial total number of atmos
data_var = ini_abun.ele_sum(data_var)

# calculating mean molecular weight, dz, and dzi and plotting TP
data_atm = make_atm.f_mu_dz(data_var, data_atm, output)

# after dz is calculated
# Only setting up ms (the species molecular weight) if vulcan_cfg.use_moldiff == False
make_atm.mol_diff(data_atm)

# specify the BC
make_atm.BC_flux(data_atm)


# ============== Execute VULCAN  ==============
# time-steping in the while loop until conv() returns True or count > count_max 

# setting the numerical solver to the designated one in vulcan_cfg
_solvers = {'Ros2': Ros2, 'Rodas3': Rodas3, 'ODESolver': ODESolver}
solver = _solvers[_cfg.solver.ode_solver]()

# Setting up for photo chemistry
if _cfg.photochemistry.use_photo:
    rate.make_bins_read_cross(data_var, data_atm)
    #rate.read_cross(data_var)
    make_atm.read_sflux(data_var, data_atm)
    
    # computing the optical depth (tau), flux, and the photolisys rates (J) for the first time
    solver.rt(data_var, data_atm)
    # they will be updated in Integration by the assigned frequency
    
    # removing rates
    data_var = rate.remove_rate(data_var)

integ = Integration(solver, output)
# Assgining the specific solver corresponding to different B.C.s
solver.naming_solver(data_para)
 
# Running the integration loop
integ(data_var, data_atm, data_para, make_atm)

output.save_out(data_var, data_atm, data_para, dname)
