"""Sphinx configuration for the neoVULCAN documentation."""

import os
import sys

# Make the neoVULCAN source tree importable for autodoc.
# Layout assumption: this file lives in <repo>/neoVULCAN_docs/neoVULCAN/docs_src/
# and the code lives in <repo>/neoVULCAN/.  Adjust the relative path here if
# you reorganise the documentation branch.
_neovulcan_root = os.path.abspath('../../../neoVULCAN')
sys.path.insert(0, _neovulcan_root)
sys.path.insert(0, os.path.join(_neovulcan_root, 'src'))

# Several modules in src/ (e.g. build_atm.py, rates.py, radiative_transfer.py)
# open data files via paths that are *relative* to the neoVULCAN root
# (e.g. ``thermo/all_compose.txt``) and call
# ``neovulcan_runtime.get_cfg()`` at import time. We register a
# builder-init hook that
#   (a) changes into the neoVULCAN root so relative paths resolve, and
#   (b) loads the in-tree ``vulcan_cfg.toml`` into the runtime singleton
#       so autodoc imports do not raise.
def _bootstrap_neovulcan(app):
    if not os.path.isdir(_neovulcan_root):
        return
    os.chdir(_neovulcan_root)
    try:
        from neovulcan_config import VulcanConfig  # noqa: WPS433
        from neovulcan_runtime import set_cfg, get_cfg  # noqa: WPS433
        try:
            get_cfg()
        except RuntimeError:
            toml_path = os.path.join(_neovulcan_root, 'vulcan_cfg.toml')
            if os.path.isfile(toml_path):
                set_cfg(VulcanConfig.from_toml(toml_path, base_dir=_neovulcan_root))
    except Exception:
        # If config bootstrap fails (e.g. pydantic mocked), autodoc will
        # still emit warnings but the rest of the build proceeds.
        pass


def setup(app):
    app.connect('builder-inited', _bootstrap_neovulcan)

# -- Project information -----------------------------------------------------

project = 'neoVULCAN'
copyright = '2026, Shang-Min Tsai and contributors'
author = 'Shang-Min Tsai'
release = '0.1'
version = '0.1'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Math rendering
mathjax3_config = {
    'tex': {
        'macros': {
            'd': r'\mathrm{d}',
            'e': r'\mathrm{e}',
            'Dz': r'\partial_z',
            'Kzz': r'K_{zz}',
            'Dzz': r'D_{zz}',
        }
    }
}

# Napoleon (NumPy / Google docstrings)
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = False
napoleon_use_param = True
napoleon_use_rtype = True

# Autodoc behaviour
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
    'show-inheritance': True,
    'member-order': 'bysource',
}
autodoc_mock_imports = [
    'jax', 'jaxlib', 'pyfastchem', 'PIL', 'matplotlib', 'sympy',
    # Pydantic-driven config: keep autodoc lightweight by mocking pydantic
    # (the model classes are still documented from their source code).
    # Note: pydantic is *not* mocked — neovulcan_config defines real
    # Pydantic models that we want autodoc to inspect.
    # Optional radiative-transfer backend; mock so autodoc on
    # radiative_transfer.py does not require the user to install it.
    'disortpp',
    # 3.10 backport for tomllib (irrelevant on the doc build host).
    'tomli',
    # chemistry_jax.py is auto-generated by make_chemistry_jax.py and only
    # exists in a populated working tree; mock it so autodoc does not fail
    # when run from the documentation branch.
    'chemistry_jax',
]

# Intersphinx
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable', None),
    'scipy': ('https://docs.scipy.org/doc/scipy', None),
}

# -- HTML output -------------------------------------------------------------

html_theme = 'furo'
html_theme_options = {
    'sidebar_hide_name': False,
    'navigation_with_keys': True,
}

html_static_path = ['_static']
html_title = 'neoVULCAN documentation'

# Allow the build to succeed even if a few referenced files are missing.
nitpicky = False

# A few entries in references.rst are kept as background reading and are
# not directly cited in the text yet; silence the corresponding warnings.
suppress_warnings = ['ref.citation']
